### ISSUE TITLE
selector is not a function

### ISSUE THREAD

**Issue by deepj** [rematch/rematch#309]
Hello,
there is no clear from the documentation how to use selectors.

```javascript
...
import { init, dispatch } from '@rematch/core'
import { select } from '@rematch/select'

const taxonomy = {
  state: {
    ...
  },
  reducers: {
    ...
  },
  selectors: {
    getAllByProject: (state, projectId) => {
      ...
    }
  }
 }

const store = init({
  models: { taxonomy },
  plugins: [select]
})

const mapState = (state) => ({
  projects: select.getAllByProject(state, '1')
})

connect(mapState, mapDispatch)(TaxonomyTree)
```

I thought I'd followed the selectors API documentation. But I'm getting only `__WEBPACK_IMPORTED_MODULE_7__rematch_select__.select.getAllByProject is not a function`. Is it possible to extend documentation about more examples how to use selectors?

```
@rematch/core: 0.5.3
@rematch/select: 0.2.2
```

**Comment by blairbodnar** [comment]
Hi @deepj ,

I think you just forgot the model name. In your `mapState` function,  try changing:

```js
select.getAllByProject(state, '1')
```
to
```js
select.taxonomy.getAllByProject(state, '1')
```

That being said, you may find that it might be best to not even use the select plugin right now. We've been having a lot of discussions lately over in #270 about it. I personally am starting to just write my selectors outside of the model like this [comment](https://github.com/rematch/rematch/issues/270#issuecomment-372547336).

Hope that helps!

**Comment by deepj** [comment]
@blairbodnar 
Thanks, unfortunately, `select.taxonomy.getAllByProject(state, '1')` occurs the same error. What's strange. Unfortunately, I haven't understood your example in #270. I'm quite a new in the frontend development when the most of time I've been a backend developer.

**Comment by mgutz** [comment]
I think you're not initializing the plugin correctly

```
import selectorsPlugin, {select} from '@rematch/select'

const store = ({
    plugins: [selectorsPlugin()],
})
```

**Comment by blairbodnar** [comment]
No prob @mgutz , welcome to Front-End land 😀

Double check you're initializing correctly like @mgutz mentioned above. If that doesn't work, here's a quick demo I put together that you can play around with: https://codesandbox.io/s/404vqv9wmw

**Comment by eric-burel** [comment]
Hi right now my `select` objet is empty, I get the same error and I don't get why. Do you have any idea how to debug this (test if the plugin is loaded, if the selectors are processed etc.)? Usually i'd open the node_modules code and add a few console log but here it is already minified, I can't tell what's happening..

**Comment by eric-burel** [comment]
Hi, thanks for the one file demo I'll try that, but when I tested on the same file it did not work, select was still equal to `{}`after the call to init. I'll test that and tell you.

**Comment by denisw** [comment]
@eric-burel I fixed the problem by updating `@rematch/core` to `1.0.0-alpa.4`. Apparently, the latest stable version of `@rematch/select` is not compatible with the current stable version of `@rematch/core`. Perhaps it should?

**Comment by danawoodman** [comment]
I believe this is still an issue. I installed `@rematch/select` `v0.3.0` and the following returns undefined:

```js
import { getSelect } from '@rematch/select'

console.log(getSelect) // undefined
```

**Comment by jackwilsdon** [comment]
@danawoodman `getSelect` is part of the new `@rematch/select` beta. [Here is the latest version](https://github.com/rematch/rematch/tree/0.6.0/plugins/select) which you'll get from `npm install`.

**Comment by danawoodman** [comment]
Do I need to install with git or can a `beta` version be pushed to npm?

**Comment by jackwilsdon** [comment]
It looks like `@rematch/core@1.0.0-beta.5` and `@rematch/select@1.0.2` are available on npm right now (you need beta core to use the beta select plugin). You can install them like this: `npm install --save @rematch/core@1.0.0-beta.5 @rematch/select@1.0.2`.

**Comment by d3dc** [comment]
I'm closing this since a lots changed with `selectors`. There's a breaking API change and new docs. Let me know if I upset the balance of the force.
