### ISSUE TITLE
not async effects are not typed correctly 

### ISSUE THREAD

**Issue by daniel-stoll** [rematch/rematch#673]
**Describe the bug**
Payload is not infered correctly

**To Reproduce**
Create an effect that is not async
```	
effects: (dispatch: Dispatch) => ({
	async incrementAsync() {
		await delay(500)
		dispatch.dolphins.increment()
	},
	decrementDolphin(count:number){
		dispatch.dolphins.doSomething(count)
	}
}),
```

call the effect from another effect or mapDispatch will result in a typing error:
```dispatch.dolphins.decrementDolphin(123)```

> 
> No overload matches this call.
>   Overload 1 of 3, '(action: Action<any, any>): Promise<Dispatch<Action<any, any>>> | Promise<Action<any, void>>', gave the following error.
>     Argument of type '123' is not assignable to parameter of type 'Action<any, any>'.
>   Overload 2 of 3, '(action: Action<any, void>): Promise<Action<any, void>> | Promise<Dispatch<Action<any, void>>>', gave the following error.
>     Argument of type '123' is not assignable to parameter of type 'Action<any, void>'.ts(2769)

**Expected behavior**
Typed payload or atleast no typing error

**Comment by semoal** [comment]
Interesting, in what version is happening your issue?

We fixed this issue on version 1.2.0

**Comment by daniel-stoll** [comment]
i used 1.2.0 ;)
checked out the repo and tried it there aswell and it is not working

**Comment by Javi** [comment]
I can second that this is still happening, using `createModel` as well.

**Comment by Neddz** [comment]
I can confirm this is happening to me as well using `"@rematch/core": "^1.2.0"` and `createModel()`

**Comment by Krasnov8953** [comment]
Anybody found the solution for this?

**Comment by daniel-stoll** [comment]
I think i found the bug in the index.d.ts.
The type ExtractRematchDispatchersFromEffectsObject only gets passed down ExtractRematchDispatcherAsyncFromEffect for all effects.
Since we can't use an optional type here, it is better to extend the ExtractRematchDispatcherAsyncFromEffect with the missing synchronous dispatched functions.
In my project this does the trick, however, I wasn't able to get the typings working in the repo...
Can somebody confirm, that the changes are working for them too?

```
export type ExtractRematchDispatcherAsyncFromEffect<
	E
	> = E extends () => any
	? RematchDispatcher<void, void>
	: E extends (payload: infer P) => any
	? RematchDispatcher<P, void>
	: E extends (payload: infer P, meta: infer M) => any
	? RematchDispatcher<P, void>
	: E extends () => Promise<any>
	? RematchDispatcherAsync<void, void>
	: E extends (payload: infer P) => Promise<any>
	? RematchDispatcherAsync<P, void>
	: E extends (payload: infer P, meta: infer M) => Promise<any>
	? RematchDispatcherAsync<P, void>
	: RematchDispatcherAsync<any, any>
```

**Comment by Krasnov8953** [comment]
> I think i found the bug in the index.d.ts.
> The type ExtractRematchDispatchersFromEffectsObject only gets passed down ExtractRematchDispatcherAsyncFromEffect for all effects.
> Since we can't use an optional type here, it is better to extend the ExtractRematchDispatcherAsyncFromEffect with the missing synchronous dispatched functions.
> In my project this does the trick, however, I wasn't able to get the typings working in the repo...
> Can somebody confirm, that the changes are working for them too?
> 
> ```
> export type ExtractRematchDispatcherAsyncFromEffect<
> 	E
> 	> = E extends () => any
> 	? RematchDispatcher<void, void>
> 	: E extends (payload: infer P) => any
> 	? RematchDispatcher<P, void>
> 	: E extends (payload: infer P, meta: infer M) => any
> 	? RematchDispatcher<P, void>
> 	: E extends () => Promise<any>
> 	? RematchDispatcherAsync<void, void>
> 	: E extends (payload: infer P) => Promise<any>
> 	? RematchDispatcherAsync<P, void>
> 	: E extends (payload: infer P, meta: infer M) => Promise<any>
> 	? RematchDispatcherAsync<P, void>
> 	: RematchDispatcherAsync<any, any>
> ```

No itsn't working for me, "@rematch/core": "^1.2.0", model initialized without createModel helper.

**Comment by daniel-stoll** [comment]
tried it with the new version 1.4.0 and it is still not working. It is not that bad since the effects most of the time are async.
