### ISSUE TITLE
Expo updates clearing all the persist data

### ISSUE THREAD

**Issue by shubhangedufund** [rematch/rematch#863]
**Summary**

Hello,

We are using persist plugin in our code with rematch. The storage used in persist plugin is AsyncStorage. The functionality is working fine and the data is persisted in both app kill and background state till I do expo publish.

Once I did expo publish, the changes are also reflected but all the data is lost. I am not able persist the user.

Attaching Android Manifest, AppDelegate and store file.

Please find the below files for your reference -

[AppDelegate.txt](https://github.com/expo/expo/files/5931103/AppDelegate.txt)

[store.txt](https://github.com/expo/expo/files/5931115/store.txt)

[AndroidManifest.txt](https://github.com/expo/expo/files/5931095/AndroidManifest.txt)

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android, iOS

**SDK Version (managed workflow only)**

_No response_

**Environment**

 Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.19.1 - ~/.nvm/versions/node/v12.19.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v12.19.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 27, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.10 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^4.4.0 => 4.4.3 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

Build an release version of the app
Check if persist is working
Do expo-publish
Persist is not working

**Comment by semoal** [comment]
What version of Rematch are you using mate? I'll try to reproduce as soon as possible.

**Comment by shubhangedufund** [comment]
Hey @semoal 

Thanks for such a quick response. Please find below the details of rematch version:

```
@rematch/core": "^2.0.0-next.6"
@rematch/loading": "^1.2.1"
@rematch/persist": "^1.1.6"
```

**Comment by semoal** [comment]
Probably the problem is that your version is not correct linked.
V1 versions are compatible with 1.x.x versions
v2 versions are compatible with 2.x.x versions.

We just released to `latest` version 2, so please update your dependencies and give it a try.

```
npx update-by-scope @rematch 
```

Your versions should look like this:

```
@rematch/core": "^2.0.0"
@rematch/loading": "^2.0.0"
@rematch/persist": "^2.0.0"
```

**Comment by shubhangedufund** [comment]
@semoal I upgraded the rematch to latest version but the issue still persist.

**Comment by semoal** [comment]
Alright, let me investigate further

**Comment by shubhangedufund** [comment]
@semoal Any further update on this?

**Comment by semoal** [comment]
Couldn't publish it yet, let me a few days to review it.

**Comment by semoal** [comment]
Finally I could publish the application and for me it's working fine.

Could you try it?
https://github.com/semoal/rematch-expo-persist

**Comment by shubhangedufund** [comment]
@semoal I saw the repo which you shared...the repo is in expo (with expo version 37)....could you please try ejecting the above project and then do an ota....as for me the functionality was working fine till I was on expo environment...as I did expo eject the ota updates cleared all the persist data

**Comment by semoal** [comment]
> @semoal I saw the repo which you shared...the repo is in expo (with expo version 37)....could you please try ejecting the above project and then do an ota....as for me the functionality was working fine till I was on expo environment...as I did expo eject the ota updates cleared all the persist data

Could you share with me that changes? I'm not an expert with expo and ejecting things on React Native. Probably will be easier if you provide a repo and i'll debug the redux issue. 
I'm practically sure that the issue comes from redux-persist library, but let's reproduce it =)

**Comment by shubhangedufund** [comment]
@semoal Sorry for the delay. But I was not able to run the repo past splash-screen. Also on further investigating, I found that data is present in asyncstorage, but when I am accessing state with useSelector the state is restored to intial state. This is happening only after doing an ota update
